project:                
  type: website          
  output-dir: docs       
  
website:
  title: "Análisis Mercado Laboral"            #- 
  favicon: imagenes/my_fav_icon_robot.png     #- 
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    logo: "imagenes/my_fav_icon_robot.png  "           #---
    background: "#0e577f"    #- color de la navbar
    #foreground: "#FF0000"    #- color navigation elements, text and links that appear in the navbar.
    #left: 
    right:
      - icon: house-door #Cambie el ícono de la casa a la derecha
        href: index.html
      - text: "Trabajo individual"   #---
        href: my_trabajo_BigData.qmd   
      - icon: github
        href: https://github.com/ricardofreirev    #- pon tu usuario Github
      - icon: envelope
        url: "mailto:rifrei@alumni.uv.es"            #- pon tu e-mail
  page-footer:
    border: true
    background: "#0e577f"         #--
    left: "© 2023 Ricardo Freire"   #--
    center: "Hecho con [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/ricardofreirev     #- pon tu usuario Github
      - icon: envelope
        url: "mailto:rifrei@alumni.uv.es"            #- pon tu e-mail
    
format:
  html:
    theme: cosmo         #- https://quarto.org/docs/output-formats/html-themes.html
    mainfont: Serif
    highlight-style: a11y   #-
    css: my_styles.css      #- si queréis añadir cosas
    page-layout: full
    toc: true
    toc-location: left
    toc-title: "Índice"
    code-copy: true
    code-overflow: wrap    
    code-fold: show
    code-line-numbers: true

# Enable CC licence appendix
#license: "CC BY"

lang: es  

# Default execute options
execute:
  echo: true
  message: false
  warning: false
  eval: true
  code-fold: show
  #fig-align: center
  #freeze: true  #- des-comentar cuando estéis tuneando el blog
                 #- https://quarto.org/docs/projects/code-execution.html#freeze
    

#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999) #- para quitar la notación científica  
